version: 2.1
orbs:
    node: circleci/node@5.0.2

workflows:
    test:
        jobs:
            - node/test:
                name: 'test'
                version: '18.3.0'
                test-results-for: jest
                cache-version: default
            - node/test:
                name: 'test:e2e'
                version: '18.3.0'
                setup: 
                    - setup_remote_docker
                    - run: docker --version
                    - run: docker pull appropriate/curl
                    - run: npm run build
                run-command: 'test:e2e'
                test-results-for: jest
                cache-version: default
            - node/test:
                name: 'test:types'
                version: '18.3.0'
                run-command: 'test:types'
                cache-version: default
            - node/test:
                name: 'test:format'
                version: '18.3.0'
                run-command: 'test:format'
                cache-version: default