version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '12.18.4'
    steps:
      - setup_remote_docker
      - checkout
      - run: node --version
      - run: npm --version
      - run: docker --version
      - run: env
      - run: docker pull appropriate/curl
      - run: mkdir -p _out/unit _out/e2e
      - node/with-cache:
          steps:
            - run: npm ci
            - run: npm install --no-save tap-xunit
            - run: npm test --  --timeout=5m --tap --no-color| npx tap-xunit > _out/unit/test.xml
            - run: npm run build
            - run: npm run test:e2e --  --timeout=10m --tap --no-color| npx tap-xunit > _out/e2e/test.xml
      - store_test_results:
          path: _out
      - store_artifacts:
          path: _out  
workflows:
    build-and-test:
      jobs:
        - build-and-test